name: Mojot Napreden DevOps Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Вака дефинирано со коса црта (/), GitHub го прави поднасловот во менито
    name: build & test / node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Kloniraj go kodot
        uses: actions/checkout@v4

      - name: Postavi Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Testiraj
        run: node --version
